# Generated by Django 4.2.18 on 2025-01-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
    ]
