# Generated by Django 4.2.18 on 2025-01-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_prescription_prescriptionitem_preassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preassessment',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preassessment',
            name='heart_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preassessment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preassessment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preassessment',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preassessment',
            name='temperature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
