# Generated by Django 4.2.18 on 2025-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_prescription_prescriptionitem_preassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a', models.CharField(max_length=75)),
                ('drub_b', models.CharField(max_length=75)),
                ('severity', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('management', models.TextField()),
            ],
        ),
    ]
