# Generated by Django 4.2.18 on 2025-02-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_druginteractions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druginteractions',
            old_name='drub_b',
            new_name='drug_b',
        ),
    ]
