# Generated by Django 4.2.18 on 2025-02-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassessment',
            name='chronic_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preassessment',
            name='smoking_history',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
