# Generated by Django 4.2.18 on 2025-02-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_preassessment_chronic_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preassessment',
            name='recommendations',
        ),
    ]
