# Generated by Django 4.2.18 on 2025-02-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_preassessment_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassessment',
            name='title',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
