# Generated by Django 4.2.18 on 2025-02-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_preassessment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassessment',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preassessment', to='api.prescription'),
        ),
        migrations.AlterField(
            model_name='preassessment',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
