# Generated by Django 4.2.18 on 2025-02-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_preassessment_prescription_alter_preassessment_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAvailableDosages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('available_dosage', models.TextField()),
                ('form', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='street_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state_province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
