# Generated by Django 4.2.18 on 2025-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_drugavailabledosages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugavailabledosages',
            name='form',
            field=models.CharField(max_length=100),
        ),
    ]
