# Generated by Django 4.2.18 on 2025-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassessment',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
