# Generated by Django 4.2.18 on 2025-02-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_preassessment_blood_pressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preassessment',
            name='symptoms',
        ),
    ]
