# Generated by Django 4.2.18 on 2025-02-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_preassessment_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
