# Generated by Django 5.1.5 on 2025-02-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_patient_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preassessment',
            old_name='notes',
            new_name='medical_history',
        ),
        migrations.RemoveField(
            model_name='preassessment',
            name='title',
        ),
        migrations.AddField(
            model_name='preassessment',
            name='alcohol_consumption_history',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
