# Generated by Django 5.1.5 on 2025-03-03 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_patient_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='time_created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
